# This is a basic
name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:
  # Triggers the workflow on push or  the master branch
  push:
    branches: [ master  ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    if: ${{github_event_name =='push' }}
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: n1dprime/dockerpush@main
        with:
           who-to-greet: 'Mona the Octocat'
  
  manual:
  
   if: ${{github_event_name == 'workflow_dispatch'}}      
   runs-on: ubuntu-latest
   
   steps:
    - run: echo 'hello this is manual test'
